### ISSUE TITLE
Reorder: Gamedev

### ISSUE THREAD

**Issue by kassane** [kristoff-it/allyourcodebase.com#14]
I think it is interesting to separate some of the items mentioned in Gamedev, because not everything is unique to this area.

Examples are some bindings, wrappers, network, Gui and so on.

**Comment by kristoff-it** [comment]
I thought about this and my conclusion is that allyourcodebase should be use-case based and not be a 1:1 alternative to "awesome zig" lists. More specifically, the expectation is that somebody that is interested in a type of development can go into a section and find everything that it's available. I would like at some point for each section to even have a "get started" guide.

This means that both gamedev and web will have a 'database' section for example, and that's fine.

Same with GUI: some GUI frameworks will be more suitable for gamedev, some others will only be listed other sections (eg desktop applicaton development).

I'm closing this issue because in my mind this seems a viable path forward, but I'm happy to continue the discussion if you want.
